version: "3.3"
services:
  resonite:
    image: dexythepuppy/resonite-headless:latest
    container_name: resonite-headless
    # Optionally define a hostname. Useful for log file naming.
    #hostname: resonite-headless 
    tty: true
    stdin_open: true
    environment:
      ALLOWMODS: 0
      STEAMBETA: headless
      STEAMBETAPASSWORD: CHANGEME
      STEAMLOGIN: "USER PASSWORD"
    volumes:
      - "./Config:/Config:ro"
      - "./Logs:/Logs"
      - "./RML:/RML"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
